### PR TITLE
Change default pool size to 2

### PR DESCRIPTION
**Pull request by schneems**
I have a customer who was running 20 unicorn workers on a performance L dyno. They were using default settings and wondering why database time was so slow.

I'm proposing we set this to a slightly higher default of 2.

In the long term I propose we pull some internal data to better set this default value.

I.e. collect the maximum database connections used by all apps on the platform that are using this buildpack as well as the max number of dynos and whether or not they're using preboot.

Another question is: is there some metric we could provide that would help customers set this value? I.e. time spent waiting on a getting a pgbouncer connection?

### CODE REVIEW

**Comment by mble** [comment]
@schneems Setting more robust defaults is something I'm +1 on.

> is there some metric we could provide that would help customers set this value? I.e. time spent waiting on a getting a pgbouncer connection?

PgBouncer will log some aggregated stats, including `wait time` periodically, with the default of every 6 seconds. If this is elevated, adjusting the default pool size could be considered.

Normally it's a matter of something like

````
(PGBOUNCER_RESERVE_POOL_SIZE + PGBOUNCER_DEFAULT_POOL_SIZE) * number of dynos <= postgres max_connections
```` 

to calculate what your default pool size _could_ be. There are some more sophisticated ways of doing this, but typically requires profiling from the admin database, which given it's per dyno is tricky to aggregate statistics without having a sidecar that runs queries against that database and outputs them in addition to the aggregated stats.

**Comment by schneems** [comment]
Also need to update devcenter docs if this merges https://devcenter.heroku.com/articles/on-dyno-postgres-connection-pooling

**Comment by schneems** [comment]
Who makes the final call here?

**Comment by binarycleric** [comment]
@schneems Have you done any testing on if this impacts lower tier dynos? This change effectively doubles the number of connections required per-dyno and some customers are already close to that limit.

\*sigh\* I wish we had more insights into these things.

Until we can get some kind of smarter configuration here I'm -1 (weakly held opinion) on this change. Larger customers like that should be tweaking their configurations for their needs as opposed to putting lower-tier users in a potentially bad situation.

**Pull request closed without merging**
