### PR TITLE
Support Heroku-18 stack image

### PR DESCRIPTION
**Pull request by tt**
I tried using the stack image's version of stunnel instead of vendoring a binary that's already there.

### CODE REVIEW

**Comment by ojacobson** [comment]
The generated stunnel config doesn't work with heroku-18's `stunnel`:

```
[!] /app/vendor/stunnel/stunnel-pgbouncer.conf:3: "options = NO_SSLv2": Illegal TLS option
```

**Comment by ojacobson** [comment]
Nope, still no:

```
[!] /app/vendor/stunnel/stunnel-pgbouncer.conf:3: "options = SINGLE_ECDH_USE": Illegal TLS option
```

**Comment by binarycleric** [comment]
fwiw, I'm working on [a branch](https://github.com/heroku/heroku-buildpack-pgbouncer/tree/no-stunnel-rebase) that removes the need for stunnel entirely. Greg started on it back in 2016 and I want to make sure it is stable enough to release.

**Comment by binarycleric** [comment]
Opened https://github.com/heroku/heroku-buildpack-pgbouncer/pull/104 and I'm doing some more testing. This'll make getting on `heroku-18` a bit easier.

**Comment by binarycleric** [comment]
https://github.com/heroku/heroku-buildpack-pgbouncer/pull/104 has been merged so we can drop any stunnel related config from this branch.

**Comment by tt** [comment]
@binarycleric, I updated this to remove the stunnel related commits and rebuild the binary based on the released stack image.

**Comment by bvallelunga** [comment]
@tt any updates on this issue? Heroku-18 is still not working for me with the bg-bouncer?

**Comment by jchatel** [comment]
+1

**Comment by beanieboi** [comment]
hey everybody, sorry for the delay on this. With Dreamforce coming up next week we are pretty filled up with work. Really sorry for this. To resolve your immediate issue you can use this branch of the buildpack

`heroku buildpacks:add https://github.com/heroku/heroku-buildpack-pgbouncer#tt/support-heroku-18-stack-image`

**Comment by bvallelunga** [comment]
@beanieboi I tried this branch and it seems to not be working.

**Comment by beanieboi** [comment]
@bvallelunga can you give me a little more detail on that, is there something specific about your setup? is there a error message that you see. i created a new Rails application that uses this branch of the pgbouncer buildpack and i was able to get it up and running.

**Comment by richsoni** [comment]
@beanieboi we are seeing the same issue.  It's tricky for our setup because it seems that DataDog is broken on Heroku-18 for our setup https://github.com/DataDog/heroku-buildpack-datadog/issues/67

```vendor/pgbouncer/bin/pgbouncer: error while loading shared libraries: libevent-2.0.so.5: cannot open shared object file: No such file or directory```

**Comment by richsoni** [comment]
Absolutely.  Thanks for the response @tt 

```
$ heroku buildpacks -a rooms-staging-we
=== rooms-staging-we Buildpack URLs
1. https://github.com/DataDog/heroku-buildpack-datadog.git
2. heroku/nodejs
3. heroku/ruby
4. https://github.com/heroku/heroku-buildpack-pgbouncer#tt/support-heroku-18-stack-image
```

```
$ heroku stack -a rooms-staging-we
=== ⬢ rooms-staging-we Available Stacks
  cedar-14
  container
  heroku-16
* heroku-18
```

**Comment by ivanovv** [comment]
OK, we tried upgrading to Cedar-18 and and it all went pete tong

Is there a guide how to get `heroku-buildpack-pgbouncer` and `Heroku-18` playing nicely together? 

Is this the one?
>hey everybody, sorry for the delay on this. With Dreamforce coming up next week we are pretty filled up with work. Really sorry for this. To resolve your immediate issue you can use this branch of the buildpack

> `heroku buildpacks:add https://github.com/heroku/heroku-buildpack-pgbouncer#tt/support-heroku-18-stack-image`

**Comment by beanieboi** [comment]
Hey @ivanovv 
could you please provide us some more details on what went wrong. we are intending to ship this branch, it would help us tremendously if you can provide us with feedback before we ship this

**Comment by ivanovv** [comment]
Sorry, wasn't clear enough. 
I meant that we had a problem updating to Heroku-18 *without* making changes to the buildpack.

And my question was – what is the current recommended way to use pgBouncer buildpack?

**Comment by beanieboi** [comment]
@ivanovv if we merge this PR then there is no change on your side needed. right now, the master branch does not work with heroku-18. if you want to try out this branch you can use the following command to replace the pgbouncer buildpack with the branch version

```
heroku buildpacks:add https://github.com/heroku/heroku-buildpack-pgbouncer#tt/support-heroku-18-stack-image
```

**Comment by richsoni** [comment]
@beanieboi I got it to work for our app with this branch.  I think my buildpack ordering was wrong when I initially tested.

**Pull request merged**
