### PR TITLE
Update buildpack to use pgbouncer 1.23.1

### PR DESCRIPTION
**Pull request by xiaolin-ninja**
https://www.pgbouncer.org/2024/08/pgbouncer-1-23-1
https://www.pgbouncer.org/2024/07/pgbouncer-1-23-0

Notable changes since last update (1.17):

- User Name Maps for Authentication Configuration (1.23.0)
- Allows specifying user name maps in the authentication configuration.
- Rolling Restarts (1.23.0) [ _minor breaking change_. Now use SIGQUIT instead of SIGTERM ]
- Improved support for handling replication connections through PgBouncer. (1.23.0)
- Introduced track_extra_parameters, allowing the tracking of more parameters in transaction pooling mode. (1.22.0)
- SQLSTATE codes are now forwarded during the authentication phase, enhancing error handling. (1.22.0)
- Allows the use of the PGOPTIONS environment variable to set PostgreSQL parameters at startup. (1.22.0)
- Added IntervalStyle to the tracked parameters by default. (1.22.0)

### CODE REVIEW

**Comment by troycoll** [comment]
Dev environment testing:
Follow these instructions to add pgbouncer buildpack to an app
Provision a Postgres standard-0
`heroku logs -t -a app-name` to tail the app's logs:
```
2024-08-12 16:27:25.689 UTC [16] LOG process up: PgBouncer 1.23.1, libevent 2.1.12-stable (epoll), adns: evdns2, tls: OpenSSL 3.0.2 15 Mar 2022
```

**Review by coreypurcell — APPROVED** [review]
seems fine, but do we need to do anything to support the PGOPTIONS changes?

**Comment by troycoll** [comment]
@coreypurcell I'm not sure if we want to do that, given that PGOPTIONS supports a dynamic [list of parameters](https://www.postgresql.org/docs/15/protocol-flow.html#PROTOCOL-ASYNC) via the `track_extra_parameters` field in PgBouncer config. We can always make additions to [PgBouncer config env vars](https://devcenter.heroku.com/articles/best-practices-pgbouncer-configuration#configuring-the-client-side-buildpack) or [PgSettings](https://devcenter.heroku.com/articles/heroku-postgres-settings) if there are specific requests.

**Comment by troycoll** [comment]
@edmorley this is ready to release at your convenience!

**Comment by edmorley** [comment]
Please can I have a review for #196.

**Pull request merged**
