### PR TITLE
Remove stunnel in favor of pgbouncer TLS

### PR DESCRIPTION
**Pull request by gregburek**
As of v1.7, pgbouncer supports TLS on client and server side (https://pgbouncer.github.io/config.html#tls-settings). This PR is is built on #67 and is to see if stunnel can be removed as a dependency. 

TODO:
- [ ] test with RDS for `option = no_ticket` problems
- [ ] update READMEs and all other docs.

### CODE REVIEW

**Comment by gregburek** [comment]
Looks p good with heroku postgres:


```
2016-01-03T02:43:17.498704+00:00 app[server_worker.1]: 2016-01-03 02:43:17.498 19 LOG File descriptor limit: 10000 (H:10000), max_client_conn: 100, max fds possible: 111
2016-01-03T02:43:17.491835+00:00 app[server_worker.1]: buildpack=pgbouncer at=config-gen-end
2016-01-03T02:43:17.491904+00:00 app[server_worker.1]: buildpack=pgbouncer at=config-gen-override DATABASE_URL
2016-01-03T02:43:17.494448+00:00 app[server_worker.1]: buildpack=pgbouncer at=pgbouncer-launched pid=18 signal=SIGINT
2016-01-03T02:43:17.499591+00:00 app[server_worker.1]: 2016-01-03 02:43:17.499 19 LOG listening on 127.0.0.1:6000
2016-01-03T02:43:17.499759+00:00 app[server_worker.1]: 2016-01-03 02:43:17.499 19 LOG listening on unix:/tmp/.s.PGSQL.6000
2016-01-03T02:43:17.499765+00:00 app[server_worker.1]: 2016-01-03 02:43:17.499 19 LOG process up: pgbouncer 1.7, libevent 2.0.21-stable (epoll), adns: evdns2
2016-01-03T02:43:19.894140+00:00 app[server_worker.1]: 2016-01-03 02:43:19.894 19 LOG C-0x1d86a40: db1/u424s01rch1iun@127.0.0.1:55587 login attempt: db=db1 user=u424s01rch1iun tls=no
2016-01-03T02:43:19.908703+00:00 app[server_worker.1]: 2016-01-03 02:43:19.908 19 LOG S-0x1d8b6f0: db1/u424s01rch1iun@10.65.54.209:5572 SSL established: TLSv1.2/ECDHE-RSA-AES256-GCM-SHA384
2016-01-03T02:43:19.954587+00:00 app[server_worker.1]: 2016-01-03 02:43:19.954 19 LOG C-0x1d86d50: db1/u424s01rch1iun@127.0.0.1:55593 login attempt: db=db1 user=u424s01rch1iun tls=no
2016-01-03T02:43:19.976732+00:00 app[server_worker.1]: 2016-01-03 02:43:19.976 19 LOG C-0x1d87060: db1/u424s01rch1iun@127.0.0.1:55595 login attempt: db=db1 user=u424s01rch1iun tls=no
2016-01-03T02:43:20.011279+00:00 app[server_worker.1]: 2016-01-03 02:43:20.011 19 LOG C-0x1d87370: db1/u424s01rch1iun@127.0.0.1:55598 login attempt: db=db1 user=u424s01rch1iun tls=no
2016-01-03T02:43:20.032452+00:00 app[server_worker.1]: 2016-01-03 02:43:20.032 19 LOG C-0x1d87680: db1/u424s01rch1iun@127.0.0.1:55600 login attempt: db=db1 user=u424s01rch1iun tls=no
2016-01-03T02:43:20.065450+00:00 app[server_worker.1]: 2016-01-03 02:43:20.065 19 LOG C-0x1d87990: db1/u424s01rch1iun@127.0.0.1:55602 login attempt: db=db1 user=u424s01rch1iun tls=no
2016-01-03T02:43:20.102610+00:00 app[server_worker.1]: 2016-01-03 02:43:20.102 19 LOG C-0x1d87ca0: db1/u424s01rch1iun@127.0.0.1:55604 login attempt: db=db1 user=u424s01rch1iun tls=no
2016-01-03T02:43:20.141698+00:00 app[server_worker.1]: 2016-01-03 02:43:20.141 19 LOG C-0x1d87fb0: db1/u424s01rch1iun@127.0.0.1:55606 login attempt: db=db1 user=u424s01rch1iun tls=no
2016-01-03T02:43:19.899587+00:00 app[server_worker.1]: 2016-01-03 02:43:19.899 19 LOG S-0x1d8b6f0: db1/u424s01rch1iun@10.65.54.209:5572 new connection to server (from 172.18.237.102:35447)
```

**Comment by sobrinho** [comment]
Any news on that?

**Comment by gregburek** [comment]
This change has the potential to break RDS users of this buildpack, while using stunnel seems to be well known without burning problems. 

f we could pass `NO_TICKET` (https://github.com/heroku/heroku-buildpack-pgbouncer/commit/9f029e1f9b91dff334dc48d848ecdb53a05e2fff) to pgbouncer's TLS client there might be a way, but for now I don't see a way to preserve it.

**Comment by sobrinho** [comment]
We are unable to use this buildpack combined with pgpool buildpack because pgpool doesn't always have SSL, example: https://github.com/sobrinho/heroku-buildpack-pgpool

Would be nice to have a config env var to enable or disable stunnel then, wdyt?

**Comment by gregburek** [comment]
@sobrinho This is a new configuration, to me. Would you please detail your setup, goals and constraints here?

**Comment by sobrinho** [comment]
Well, I'm using pgpool and this buildpack is unabled to connect to pgpool because there isn't SSL there (after all it's running locally).

Would be nice to have something like `PGBOUNCER_USE_SSL` to configure if I want to require SSL or not.

This because I may want to use this buildpack to connect to a postgres database using or not using SSL, this shouldn't be required.

**Comment by gregburek** [comment]
@sobrinho Sure, but why are you using pgpool at all? Doesn't pgpool do what pgbouncer does? Why does pgbouncer need to be a client to pgpool and not the other way?

**Comment by sobrinho** [comment]
pgpool does different things and in our case, we are using it to round-robin reads across slaves.

Our problem is that pgpool uses the same number of connections between the app and pgpool to the postgres backend, so, we need the pgbouncer to keep the connections number under control.

We are using: app -> pgbouncer -> pgpool -> postgres.

**Comment by volkanunsal** [comment]
Having the same problem as @sobrinho. We need to disable TLS somehow.

**Comment by binarycleric** [comment]
Closing now that https://github.com/heroku/heroku-buildpack-pgbouncer/pull/104 is merged.

**Pull request closed without merging**
